### PR TITLE
fix(samplr): remove whitespace from Snippet's Language

### LINKED ISSUE #113: Samplr: Language names sometimes have spaces in them
While looking at the snippet tracker logs, I noticed that pom.xml files have a language name of "MAVEN POM". Since this does not match a snippet tracker language, the snippets cannot be added. I know a library is used to determine language names, but I think it would be a good idea to replace spaces with underscores. Then I can add a new language to snippet tracker to match MAVEN_POM.

(I am also guessing that it's not ideal to have spaces in the language names anyway, since the language name is used in the URI.)

### PR DESCRIPTION
**Pull request by orthros**
A snippet is accessed in the API via it's Name (which includes the
language the snippet is written in) in a URL, which cannot support
whitespace.

Adds cleanLanguage function to facilitate tests.

Fixes #113

### CODE REVIEW

**Comment by orthros** [comment]
Despite codecov failing, it is only because the line that is uncovered is a function call to newly-covered code.

**Comment by alixhami** [comment]
I'm not sure what the possible language names are, but are there other characters that need to be handled?

I think enry might be using linguist, which lists its languages here:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

Looking at that list, I think "-" should also be replaced with underscores.

**Comment by orthros** [comment]
It is similar to linguist, yes. If I understand their source correctly, the languages are defined here:

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

Why do you think "-" should be replaced with "_"? "-" is a valid character for a URL.

**Comment by alixhami** [comment]
We need to match these to our language enums. So far, our language enums do not use any hyphens. The allowed characters should be based on what we would like our language enums to look like.

@jmdobry should we allow hyphens in language enums?

**Comment by orthros** [comment]
Another option would be to maintain a mapping table between the `enry`-detected language and the Language Enums, and when a new language is added to that enum, update the mapping table if appropriate.

**Comment by alixhami** [comment]
I ultimately will need a mapping table, but I need a list of all the existing Samplr languages in order to do that. Are you able to compile a list?

Is there a reason that converting the hyphen to an underscore is specifically bad? If not, I think it would be nice to do that for consistency. Hoping to get Jason's input on having a mix of hyphens and underscores in language enums as well.

File: samplr/snippet.go [hunk 1]
```diff
@@ -536,3 +531,15 @@ func snippetsEquivalent(a SnippetVersion, b SnippetVersion) bool {
...
 }
+
+func cleanLanguage(language string) string {
+	if language == "C#" {
+		language = "CSHARP"
+	} else if language == "C++" {
+		language = "CPP"
+	}
+	language = strings.ToUpper(language)
+	language = strings.ReplaceAll(language, " ", "_")
```
Comment (jmdobry) [inline samplr/snippet.go:542]: Can we also replace `-` with `_` because that will help these values map to our Language enum values (which use underscores).

**Review by jmdobry — CHANGES_REQUESTED** [review]

File: samplr/snippet.go (hunk 1 above)
Comment (orthros) [reply samplr/snippet.go:542]: Done

**Review by jmdobry — APPROVED** [review]
